<?php

/**
 * Copyright (C) 2009-2011 Shadez <https://github.com/Shadez>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 **/

class QuestTemplate_Model_Component extends Model_Db_Component
{
	public $m_model = 'QuestTemplate';
	public $m_table = 'quest_template';
	public $m_dbType = 'world';
	public $m_fields = array(
		'entry' => 'Id',
		'Method' => array('type' => 'integer'),
		'ZoneOrSort' => array('type' => 'integer'),
		'SkillOrClassMask' => array('type' => 'integer'),
		'MinLevel' => array('type' => 'integer'),
		'MaxLevel' => array('type' => 'integer'),
		'QuestLevel' => array('type' => 'integer'),
		'Type' => array('type' => 'integer'),
		'RequiredRaces' => array('type' => 'integer'),
		'RequiredSkillValue' => array('type' => 'integer'),
		'RepObjectiveFaction' => array('type' => 'integer'),
		'RepObjectiveValue' => array('type' => 'integer'),
		'RepObjectiveFaction2' => array('type' => 'integer'),
		'RepObjectiveValue2' => array('type' => 'integer'),
		'RequiredMinRepFaction' => array('type' => 'integer'),
		'RequiredMinRepValue' => array('type' => 'integer'),
		'RequiredMaxRepFaction' => array('type' => 'integer'),
		'RequiredMaxRepValue' => array('type' => 'integer'),
		'SuggestedPlayers' => array('type' => 'integer'),
		'LimitTime' => array('type' => 'integer'),
		'QuestFlags' => array('type' => 'integer'),
		'SpecialFlags' => array('type' => 'integer'),
		'CharTitleId' => array('type' => 'integer'),
		'PlayersSlain' => array('type' => 'integer'),
		'BonusTalents' => array('type' => 'integer'),
		'RewardArenaPoints' => array('type' => 'integer'),
		'PrevQuestId' => array('type' => 'integer'),
		'NextQuestId' => array('type' => 'integer'),
		'ExclusiveGroup' => array('type' => 'integer'),
		'NextQuestInChain' => array('type' => 'integer'),
		'RewXPId' => array('type' => 'integer'),
		'SrcItemId' => array('type' => 'integer'),
		'SrcItemCount' => array('type' => 'integer'),
		'SrcSpell' => array('type' => 'integer'),
		'Title' => array('type' => 'string'),
		'Details' => array('type' => 'string'),
		'Objectives' => array('type' => 'string'),
		'OfferRewardText' => array('type' => 'string'),
		'RequestItemsText' => array('type' => 'string'),
		'EndText' => array('type' => 'string'),
		'CompletedText' => array('type' => 'string'),
		'ObjectiveText1' => array('type' => 'string'),
		'ObjectiveText2' => array('type' => 'string'),
		'ObjectiveText3' => array('type' => 'string'),
		'ObjectiveText4' => array('type' => 'string'),
		'ReqItemId1' => array('type' => 'integer'),
		'ReqItemId2' => array('type' => 'integer'),
		'ReqItemId3' => array('type' => 'integer'),
		'ReqItemId4' => array('type' => 'integer'),
		'ReqItemId5' => array('type' => 'integer'),
		'ReqItemId6' => array('type' => 'integer'),
		'ReqItemCount1' => array('type' => 'integer'),
		'ReqItemCount2' => array('type' => 'integer'),
		'ReqItemCount3' => array('type' => 'integer'),
		'ReqItemCount4' => array('type' => 'integer'),
		'ReqItemCount5' => array('type' => 'integer'),
		'ReqItemCount6' => array('type' => 'integer'),
		'ReqSourceId1' => array('type' => 'integer'),
		'ReqSourceId2' => array('type' => 'integer'),
		'ReqSourceId3' => array('type' => 'integer'),
		'ReqSourceId4' => array('type' => 'integer'),
		'ReqSourceCount1' => array('type' => 'integer'),
		'ReqSourceCount2' => array('type' => 'integer'),
		'ReqSourceCount3' => array('type' => 'integer'),
		'ReqSourceCount4' => array('type' => 'integer'),
		'ReqCreatureOrGOId1' => array('type' => 'integer'),
		'ReqCreatureOrGOId2' => array('type' => 'integer'),
		'ReqCreatureOrGOId3' => array('type' => 'integer'),
		'ReqCreatureOrGOId4' => array('type' => 'integer'),
		'ReqCreatureOrGOCount1' => array('type' => 'integer'),
		'ReqCreatureOrGOCount2' => array('type' => 'integer'),
		'ReqCreatureOrGOCount3' => array('type' => 'integer'),
		'ReqCreatureOrGOCount4' => array('type' => 'integer'),
		'ReqSpellCast1' => array('type' => 'integer'),
		'ReqSpellCast2' => array('type' => 'integer'),
		'ReqSpellCast3' => array('type' => 'integer'),
		'ReqSpellCast4' => array('type' => 'integer'),
		'RewChoiceItemId1' => array('type' => 'integer'),
		'RewChoiceItemId2' => array('type' => 'integer'),
		'RewChoiceItemId3' => array('type' => 'integer'),
		'RewChoiceItemId4' => array('type' => 'integer'),
		'RewChoiceItemId5' => array('type' => 'integer'),
		'RewChoiceItemId6' => array('type' => 'integer'),
		'RewChoiceItemCount1' => array('type' => 'integer'),
		'RewChoiceItemCount2' => array('type' => 'integer'),
		'RewChoiceItemCount3' => array('type' => 'integer'),
		'RewChoiceItemCount4' => array('type' => 'integer'),
		'RewChoiceItemCount5' => array('type' => 'integer'),
		'RewChoiceItemCount6' => array('type' => 'integer'),
		'RewItemId1' => array('type' => 'integer'),
		'RewItemId2' => array('type' => 'integer'),
		'RewItemId3' => array('type' => 'integer'),
		'RewItemId4' => array('type' => 'integer'),
		'RewItemCount1' => array('type' => 'integer'),
		'RewItemCount2' => array('type' => 'integer'),
		'RewItemCount3' => array('type' => 'integer'),
		'RewItemCount4' => array('type' => 'integer'),
		'RewRepFaction1' => array('type' => 'integer'),
		'RewRepFaction2' => array('type' => 'integer'),
		'RewRepFaction3' => array('type' => 'integer'),
		'RewRepFaction4' => array('type' => 'integer'),
		'RewRepFaction5' => array('type' => 'integer'),
		'RewRepValueId1' => array('type' => 'integer'),
		'RewRepValueId2' => array('type' => 'integer'),
		'RewRepValueId3' => array('type' => 'integer'),
		'RewRepValueId4' => array('type' => 'integer'),
		'RewRepValueId5' => array('type' => 'integer'),
		'RewRepValue1' => array('type' => 'integer'),
		'RewRepValue2' => array('type' => 'integer'),
		'RewRepValue3' => array('type' => 'integer'),
		'RewRepValue4' => array('type' => 'integer'),
		'RewRepValue5' => array('type' => 'integer'),
		'RewHonorAddition' => array('type' => 'integer'),
		'RewHonorMultiplier' => array('type' => 'integer'),
		'unk0' => array('type' => 'integer'),
		'RewOrReqMoney' => array('type' => 'integer'),
		'RewMoneyMaxLevel' => array('type' => 'integer'),
		'RewSpell' => array('type' => 'integer'),
		'RewSpellCast' => array('type' => 'integer'),
		'RewMailTemplateId' => array('type' => 'integer'),
		'RewMailDelaySecs' => array('type' => 'integer'),
		'PointMapId' => array('type' => 'integer'),
		'PointX' => array('type' => 'integer'),
		'PointY' => array('type' => 'integer'),
		'PointOpt' => array('type' => 'integer'),
		'DetailsEmote1' => array('type' => 'integer'),
		'DetailsEmote2' => array('type' => 'integer'),
		'DetailsEmote3' => array('type' => 'integer'),
		'DetailsEmote4' => array('type' => 'integer'),
		'DetailsEmoteDelay1' => array('type' => 'integer'),
		'DetailsEmoteDelay2' => array('type' => 'integer'),
		'DetailsEmoteDelay3' => array('type' => 'integer'),
		'DetailsEmoteDelay4' => array('type' => 'integer'),
		'IncompleteEmote' => array('type' => 'integer'),
		'CompleteEmote' => array('type' => 'integer'),
		'OfferRewardEmote1' => array('type' => 'integer'),
		'OfferRewardEmote2' => array('type' => 'integer'),
		'OfferRewardEmote3' => array('type' => 'integer'),
		'OfferRewardEmote4' => array('type' => 'integer'),
		'OfferRewardEmoteDelay1' => array('type' => 'integer'),
		'OfferRewardEmoteDelay2' => array('type' => 'integer'),
		'OfferRewardEmoteDelay3' => array('type' => 'integer'),
		'OfferRewardEmoteDelay4' => array('type' => 'integer'),
		'StartScript' => array('type' => 'integer'),
		'CompleteScript' => array('type' => 'integer'),
		'WDBVerified' => array('type' => 'integer'),
	);
}
?>