<?php

/**
 * Copyright (C) 2009-2011 Shadez <https://github.com/Shadez>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 **/

class WowSpell_Model_Component extends Model_Db_Component
{
	public $m_model = 'WowSpell';
	public $m_table = 'wow_spell';
	public $m_dbType = 'wow';
	public $m_fields = array(
		'id' => 'Id',
		'Category' => array('type' => 'integer'),
		'Dispel' => array('type' => 'integer'),
		'Mechanic' => array('type' => 'integer'),
		'Attributes' => array('type' => 'integer'),
		'AttributesEx' => array('type' => 'integer'),
		'AttributesEx2' => array('type' => 'integer'),
		'AttributesEx3' => array('type' => 'integer'),
		'AttributesEx4' => array('type' => 'integer'),
		'AttributesEx5' => array('type' => 'integer'),
		'AttributesEx6' => array('type' => 'integer'),
		'unk_320_1' => array('type' => 'integer'),
		'Stances' => array('type' => 'integer'),
		'unk_320_2' => array('type' => 'integer'),
		'StancesNot' => array('type' => 'integer'),
		'unk_320_3' => array('type' => 'integer'),
		'Targets' => array('type' => 'integer'),
		'TargetCreatureType' => array('type' => 'integer'),
		'RequiresSpellFocus' => array('type' => 'integer'),
		'FacingCasterFlags' => array('type' => 'integer'),
		'CasterAuraState' => array('type' => 'integer'),
		'TargetAuraState' => array('type' => 'integer'),
		'CasterAuraStateNot' => array('type' => 'integer'),
		'TargetAuraStateNot' => array('type' => 'integer'),
		'casterAuraSpell' => array('type' => 'integer'),
		'targetAuraSpell' => array('type' => 'integer'),
		'excludeCasterAuraSpell' => array('type' => 'integer'),
		'excludeTargetAuraSpell' => array('type' => 'integer'),
		'CastingTimeIndex' => array('type' => 'integer'),
		'RecoveryTime' => array('type' => 'integer'),
		'CategoryRecoveryTime' => array('type' => 'integer'),
		'InterruptFlags' => array('type' => 'integer'),
		'AuraInterruptFlags' => array('type' => 'integer'),
		'ChannelInterruptFlags' => array('type' => 'integer'),
		'procFlags' => array('type' => 'integer'),
		'procChance' => array('type' => 'integer'),
		'procCharges' => array('type' => 'integer'),
		'maxLevel' => array('type' => 'integer'),
		'baseLevel' => array('type' => 'integer'),
		'spellLevel' => array('type' => 'integer'),
		'DurationIndex' => array('type' => 'integer'),
		'powerType' => array('type' => 'integer'),
		'manaCost' => array('type' => 'integer'),
		'manaCostPerlevel' => array('type' => 'integer'),
		'manaPerSecond' => array('type' => 'integer'),
		'manaPerSecondPerLevel' => array('type' => 'integer'),
		'rangeIndex' => array('type' => 'integer'),
		'speed' => array('type' => 'integer'),
		'modalNextSpell' => array('type' => 'integer'),
		'StackAmount' => array('type' => 'integer'),
		'Totem_1' => array('type' => 'integer'),
		'Totem_2' => array('type' => 'integer'),
		'Reagent_1' => array('type' => 'integer'),
		'Reagent_2' => array('type' => 'integer'),
		'Reagent_3' => array('type' => 'integer'),
		'Reagent_4' => array('type' => 'integer'),
		'Reagent_5' => array('type' => 'integer'),
		'Reagent_6' => array('type' => 'integer'),
		'Reagent_7' => array('type' => 'integer'),
		'Reagent_8' => array('type' => 'integer'),
		'ReagentCount_1' => array('type' => 'integer'),
		'ReagentCount_2' => array('type' => 'integer'),
		'ReagentCount_3' => array('type' => 'integer'),
		'ReagentCount_4' => array('type' => 'integer'),
		'ReagentCount_5' => array('type' => 'integer'),
		'ReagentCount_6' => array('type' => 'integer'),
		'ReagentCount_7' => array('type' => 'integer'),
		'ReagentCount_8' => array('type' => 'integer'),
		'EquippedItemClass' => array('type' => 'integer'),
		'EquippedItemSubClassMask' => array('type' => 'integer'),
		'EquippedItemInventoryTypeMask' => array('type' => 'integer'),
		'Effect_1' => array('type' => 'integer'),
		'Effect_2' => array('type' => 'integer'),
		'Effect_3' => array('type' => 'integer'),
		'EffectDieSides_1' => array('type' => 'integer'),
		'EffectDieSides_2' => array('type' => 'integer'),
		'EffectDieSides_3' => array('type' => 'integer'),
		'EffectBaseDice_1' => array('type' => 'integer'),
		'EffectBaseDice_2' => array('type' => 'integer'),
		'EffectBaseDice_3' => array('type' => 'integer'),
		'EffectRealPointsPerLevel_1' => array('type' => 'integer'),
		'EffectRealPointsPerLevel_2' => array('type' => 'integer'),
		'EffectRealPointsPerLevel_3' => array('type' => 'integer'),
		'EffectBasePoints_1' => array('type' => 'integer'),
		'EffectBasePoints_2' => array('type' => 'integer'),
		'EffectBasePoints_3' => array('type' => 'integer'),
		'EffectMechanic_1' => array('type' => 'integer'),
		'EffectMechanic_2' => array('type' => 'integer'),
		'EffectMechanic_3' => array('type' => 'integer'),
		'EffectImplicitTargetA_1' => array('type' => 'integer'),
		'EffectImplicitTargetA_2' => array('type' => 'integer'),
		'EffectImplicitTargetA_3' => array('type' => 'integer'),
		'EffectImplicitTargetB_1' => array('type' => 'integer'),
		'EffectImplicitTargetB_2' => array('type' => 'integer'),
		'EffectImplicitTargetB_3' => array('type' => 'integer'),
		'EffectRadiusIndex_1' => array('type' => 'integer'),
		'EffectRadiusIndex_2' => array('type' => 'integer'),
		'EffectRadiusIndex_3' => array('type' => 'integer'),
		'EffectApplyAuraName_1' => array('type' => 'integer'),
		'EffectApplyAuraName_2' => array('type' => 'integer'),
		'EffectApplyAuraName_3' => array('type' => 'integer'),
		'EffectAmplitude_1' => array('type' => 'integer'),
		'EffectAmplitude_2' => array('type' => 'integer'),
		'EffectAmplitude_3' => array('type' => 'integer'),
		'EffectMultipleValue_1' => array('type' => 'integer'),
		'EffectMultipleValue_2' => array('type' => 'integer'),
		'EffectMultipleValue_3' => array('type' => 'integer'),
		'EffectChainTarget_1' => array('type' => 'integer'),
		'EffectChainTarget_2' => array('type' => 'integer'),
		'EffectChainTarget_3' => array('type' => 'integer'),
		'EffectItemType_1' => array('type' => 'integer'),
		'EffectItemType_2' => array('type' => 'integer'),
		'EffectItemType_3' => array('type' => 'integer'),
		'EffectMiscValue_1' => array('type' => 'integer'),
		'EffectMiscValue_2' => array('type' => 'integer'),
		'EffectMiscValue_3' => array('type' => 'integer'),
		'EffectMiscValueB_1' => array('type' => 'integer'),
		'EffectMiscValueB_2' => array('type' => 'integer'),
		'EffectMiscValueB_3' => array('type' => 'integer'),
		'EffectTriggerSpell_1' => array('type' => 'integer'),
		'EffectTriggerSpell_2' => array('type' => 'integer'),
		'EffectTriggerSpell_3' => array('type' => 'integer'),
		'EffectPointsPerComboPoint_1' => array('type' => 'integer'),
		'EffectPointsPerComboPoint_2' => array('type' => 'integer'),
		'EffectPointsPerComboPoint_3' => array('type' => 'integer'),
		'EffectSpellClassMaskA_1' => array('type' => 'integer'),
		'EffectSpellClassMaskA_2' => array('type' => 'integer'),
		'EffectSpellClassMaskA_3' => array('type' => 'integer'),
		'EffectSpellClassMaskB_1' => array('type' => 'integer'),
		'EffectSpellClassMaskB_2' => array('type' => 'integer'),
		'EffectSpellClassMaskB_3' => array('type' => 'integer'),
		'EffectSpellClassMaskC_1' => array('type' => 'integer'),
		'EffectSpellClassMaskC_2' => array('type' => 'integer'),
		'EffectSpellClassMaskC_3' => array('type' => 'integer'),
		'SpellVisual_1' => array('type' => 'integer'),
		'SpellVisual_2' => array('type' => 'integer'),
		'SpellIconID' => array('type' => 'integer'),
		'activeIconID' => array('type' => 'integer'),
		'spellPriority' => array('type' => 'integer'),
		'SpellName' => 'Locale',
		'SpellName_2' => array('type' => 'string'),
		'SpellName_5' => array('type' => 'string'),
		'SpellName_6' => array('type' => 'string'),
		'SpellName_8' => array('type' => 'string'),
		'SpellName_10' => array('type' => 'string'),
		'SpellName_11' => array('type' => 'string'),
		'SpellName_12' => array('type' => 'string'),
		'SpellName_13' => array('type' => 'string'),
		'SpellName_14' => array('type' => 'string'),
		'SpellName_15' => array('type' => 'string'),
		'SpellName_16' => array('type' => 'string'),
		'SpellNameFlag' => array('type' => 'integer'),
		'Rank' => 'Locale',
		'Rank_2' => array('type' => 'string'),
		'Rank_5' => array('type' => 'string'),
		'Rank_6' => array('type' => 'string'),
		'Rank_8' => array('type' => 'string'),
		'Rank_10' => array('type' => 'string'),
		'Rank_11' => array('type' => 'string'),
		'Rank_12' => array('type' => 'string'),
		'Rank_13' => array('type' => 'string'),
		'Rank_14' => array('type' => 'string'),
		'Rank_15' => array('type' => 'string'),
		'Rank_16' => array('type' => 'string'),
		'RankFlags' => array('type' => 'integer'),
		'Description' => 'Locale',
		'Description_2' => array('type' => 'string'),
		'Description_5' => array('type' => 'string'),
		'Description_6' => array('type' => 'string'),
		'Description_8' => array('type' => 'string'),
		'Description_10' => array('type' => 'string'),
		'Description_11' => array('type' => 'string'),
		'Description_12' => array('type' => 'string'),
		'Description_13' => array('type' => 'string'),
		'Description_14' => array('type' => 'string'),
		'Description_15' => array('type' => 'string'),
		'Description_16' => array('type' => 'string'),
		'DescriptionFlags' => array('type' => 'integer'),
		'ToolTip' => 'Locale',
		'ToolTip_2' => array('type' => 'string'),
		'Tooltip' => 'Locale',
		'ToolTip_5' => array('type' => 'string'),
		'ToolTip_6' => array('type' => 'string'),
		'ToolTip_8' => array('type' => 'string'),
		'ToolTip_10' => array('type' => 'string'),
		'ToolTip_11' => array('type' => 'string'),
		'ToolTip_12' => array('type' => 'string'),
		'ToolTip_13' => array('type' => 'string'),
		'ToolTip_14' => array('type' => 'string'),
		'ToolTip_15' => array('type' => 'string'),
		'ToolTip_16' => array('type' => 'string'),
		'ToolTipFlags' => array('type' => 'integer'),
		'ManaCostPercentage' => array('type' => 'integer'),
		'StartRecoveryCategory' => array('type' => 'integer'),
		'StartRecoveryTime' => array('type' => 'integer'),
		'MaxTargetLevel' => array('type' => 'integer'),
		'SpellFamilyName' => array('type' => 'integer'),
		'SpellFamilyFlags' => array('type' => 'integer'),
		'SpellFamilyFlags2' => array('type' => 'integer'),
		'MaxAffectedTargets' => array('type' => 'integer'),
		'DmgClass' => array('type' => 'integer'),
		'PreventionType' => array('type' => 'integer'),
		'StanceBarOrder' => array('type' => 'integer'),
		'DmgMultiplier_1' => array('type' => 'integer'),
		'DmgMultiplier_2' => array('type' => 'integer'),
		'DmgMultiplier_3' => array('type' => 'integer'),
		'MinFactionId' => array('type' => 'integer'),
		'MinReputation' => array('type' => 'integer'),
		'RequiredAuraVision' => array('type' => 'integer'),
		'TotemCategory_1' => array('type' => 'integer'),
		'TotemCategory_2' => array('type' => 'integer'),
		'AreaGroupId' => array('type' => 'integer'),
		'SchoolMask' => array('type' => 'integer'),
		'runeCostID' => array('type' => 'integer'),
		'spellMissileID' => array('type' => 'integer'),
		'PowerDisplayId' => array('type' => 'integer'),
		'unk_320_4_1' => array('type' => 'integer'),
		'unk_320_4_2' => array('type' => 'integer'),
		'unk_320_4_3' => array('type' => 'integer'),
		'spellDescriptionVariableID' => array('type' => 'integer'),
		'SpellDifficultyId' => array('type' => 'integer'),
		'f_234' => array('type' => 'integer'),
	);
}
?>