ALTER TABLE  `wow_achievement` ADD INDEX (  `id` )
ALTER TABLE  `wow_accounts` ADD INDEX (  `id` );
ALTER TABLE  `wow_accounts` ADD INDEX (  `game_id` );
ALTER TABLE  `wow_achievement_category` ADD INDEX (  `id` ,  `parentCategory` );
ALTER TABLE  `wow_achievement_criteria` ADD INDEX (  `id` ,  `referredAchievement` );
ALTER TABLE  `wow_areas` ADD INDEX (  `id` ,  `mapID` ,  `zoneID` );
ALTER TABLE  `wow_blizztracker_posts` ADD INDEX (  `tracker_post_id` );
ALTER TABLE  `wow_blog_comments` ADD INDEX (  `comment_id` ,  `blog_id` );
ALTER TABLE  `wow_bosses_abilities` ADD INDEX (  `id` ,  `boss_id` );
ALTER TABLE  `wow_bugtracker_comments` ADD INDEX (  `id` );
ALTER TABLE  `wow_bugtracker_items` ADD INDEX (  `type` );
ALTER TABLE  `wow_bugtracker_items` ADD INDEX (  `id` );
ALTER TABLE  `wow_carousel` ADD INDEX (  `id` );
ALTER TABLE  `wow_class_abilities` ADD INDEX (  `class` );
ALTER TABLE  `wow_classes` ADD INDEX (  `key` );
ALTER TABLE  `wow_enchantment` ADD INDEX (  `id` );
ALTER TABLE  `wow_extended_cost` ADD INDEX (  `id` );
ALTER TABLE  `wow_faction` ADD INDEX (  `id` );
ALTER TABLE  `wow_forum_category` ADD INDEX (  `parent_cat` );
ALTER TABLE  `wow_forum_posts` ADD INDEX (  `post_id` );
ALTER TABLE  `wow_forum_posts` ADD INDEX (  `account_id` ,  `character_guid` ,  `character_realm` );
ALTER TABLE  `wow_forum_threads` ADD INDEX (  `thread_id` ,  `account_id` ,  `character_guid` ,  `character_realm` );
ALTER TABLE  `wow_gemproperties` ADD INDEX (  `id` ,  `spellitemenchantement` );
ALTER TABLE  `wow_glyphproperties` ADD INDEX (  `type` );
ALTER TABLE  `wow_icons` ADD INDEX (  `displayid` );
ALTER TABLE  `wow_item_equivalents` ADD INDEX (  `item_horde` ,  `item_alliance` );
ALTER TABLE  `wow_item_sources` ADD INDEX (  `item` )
ALTER TABLE  `wow_item_sources` ADD INDEX (  `source` );
ALTER TABLE  `wow_item_sources` ADD INDEX (  `source_entry` );
ALTER TABLE  `wow_item_subclass` ADD INDEX (  `class` );
ALTER TABLE  `wow_item_subclass` ADD INDEX (  `subclass` );
ALTER TABLE  `wow_item_subclass` ADD INDEX (  `key` );
ALTER TABLE  `wow_itemsetdata` ADD INDEX (  `original` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item1` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item2` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item3` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item4` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item5` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item6` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item7` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item8` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item9` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item10` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item11` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item12` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item13` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item14` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item15` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item16` );
ALTER TABLE  `wow_itemsetinfo` ADD INDEX (  `item17` );
ALTER TABLE  `wow_itemsubclass` ADD INDEX (  `class` );
ALTER TABLE  `wow_itemsubclass` ADD INDEX (  `subclass` );
ALTER TABLE  `wow_itemsubclass` ADD INDEX (  `key` );
ALTER TABLE  `wow_store_categories` ADD INDEX (  `parent_id` );
ALTER TABLE  `wow_zones` ADD INDEX (  `map` ,  `area` ,  `y_min` ,  `y_max` ,  `x_min` ,  `x_max` );